In [1]:
import numpy as np

In [2]:
x = np.zeros((4,4))

In [3]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
y = np.ones((5,5))

In [5]:
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
z = np.empty((6,6))

In [7]:
z

array([[ 3.33321220e-312,  3.33287481e-312,  3.26047200e-308,
         1.33360319e+241,  5.13098582e-311,  1.53446210e-253],
       [ 2.85308965e-313,  2.00886795e-308,  1.33360296e+241,
         9.47683320e-311,  5.22150394e-215,  4.55068629e-313],
       [ 2.84327065e-308,  1.33360304e+241,  1.76252970e-310,
         2.71115985e-181,  7.52148039e-313,  3.81674046e-308],
       [ 1.33360307e+241,  2.08846826e-310,  5.00120719e-162,
         1.02800749e-312,  9.14800873e-308, -3.38460718e+125],
       [ 3.69028917e+180,  6.33016129e-307,  1.09403822e-303,
         1.27631071e-303,  1.18499507e-303,  4.30738342e-294],
       [ 5.48248396e-294,  8.49377034e+014,  1.29982152e+010,
         1.39538277e+304,  1.35751505e-043,  4.62385427e-005]])

In [8]:
list_1 = [1,2,3,4,5,7]

In [9]:
arr1 = np.array(list_1)

In [10]:
print(arr1)

[1 2 3 4 5 7]


In [11]:
arr2 = np.arange(1,100,10)

In [12]:
print(arr2)

[ 1 11 21 31 41 51 61 71 81 91]


In [13]:
arr1.shape

(6,)

In [14]:
arr2.shape

(10,)

In [15]:
x = np.zeros((10,10))

In [16]:
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [17]:
x.shape

(10, 10)

In [18]:
x_shape = x.shape

In [19]:
x_shape

(10, 10)

In [21]:
type(x_shape)

tuple

In [24]:
x.reshape((20,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
x.reshape((20,5)).shape

(20, 5)

In [26]:
x.reshape((4,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [27]:
x.dtype

dtype('float64')

In [28]:
x.reshape((2,2,5,5))

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [29]:
x.reshape((2,2,5,5)).ndim

4

In [30]:
a1 = np.zeros((4,4), dtype=int)

In [31]:
a1

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [32]:
a1.dtype

dtype('int32')