In [1]:
import numpy as np

In [2]:
list_1 = range(1000000)

In [3]:
array_1 = np.arange(1000000)

In [5]:
%time for i in range(1,10): result_1 = [x*2 for x in list_1]

Wall time: 2.24 s


In [6]:
%time for i in range(1,10): result_array_1 = array_1*2

Wall time: 48 ms


In [7]:
type(list_1)

range

In [8]:
list_2 = list(range(1000000))

In [9]:
%time for i in range(1,10): result_2 = [x*2 for x in list_2]

Wall time: 1.97 s


In [12]:
list_enum = list(enumerate(list_2))

In [13]:
type(list_enum)

list

In [14]:
list_enum[:5]

[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)]

In [15]:
for index, value in list_enum: list_2[index] = list_2[index] + 22

In [16]:
list_2[:5]

[22, 23, 24, 25, 26]

In [17]:
%time for index, value in list_enum: list_2[index] = list_2[index] + 22

Wall time: 349 ms


In [18]:
array_1

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [19]:
len(array_1)

1000000

In [20]:
len(list_2)

1000000

In [21]:
array_1 = array_1 + 22

In [22]:
array_1[:5]

array([22, 23, 24, 25, 26])

In [23]:
%time array_1 = array_1 + 22

Wall time: 8 ms


In [24]:
%time list_3 = list(range(1000000))

Wall time: 56 ms


In [25]:
%time array_2 = np.arange(1000000)

Wall time: 0 ns


In [38]:
list_4 = list(range(10))
list_5 = list(range(10))
list_6 = []

In [43]:
%time for i in range(10): list_6.append(list_5[i] + list_4[i])

Wall time: 0 ns


In [42]:
list_6

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [44]:
array_3 = np.arange(10)
array_4 = np.arange(10)

In [47]:
%time array_5 = array_3 + array_4

Wall time: 0 ns


In [46]:
array_5

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])